### ISSUE TITLE
This belongs under solar_system 

### ISSUE THREAD

**Issue by jsanc623** [god/earth#1]

**Comment by CandyOgre** [comment]
Need to create more classes #

**Comment by ewhac** [comment]
@CandyOgre: You are confusing physical placement with inheritance/hierarchy.  solar_system is composed, not inherited.  Earth is not a specialization of Sun.  And while Jupiter, Saturn, Uranus, and Neptune share similarities with Sun, ultimately they are all _siblings_ deriving from the same root classes.

Recommend closing this as NOT_A_BUG.

**Comment by Noosphericus** [comment]
http://skinphoniqa.wixsite.com/skinphoniqa
