### ISSUE TITLE
[BUG] `<Human>.IQ` is lower than `Human.MinIQ`

### ISSUE THREAD

**Issue by Alexejhero** [god/earth#17]
**Describe the bug**
The `IQ` property of the `SoftwareUser` class, which extends `Human`, is almost always lower than the static field `Human.MinIQ`.

**Code**
```cs
SoftwareUser[] randomUsers = Earth.GetRandomObjects<SoftwareUser>(10000);
bool lower = 0;
foreach (SoftwareUser user in randomUsers) 
{
    if (user.IQ < Human.MinIQ) lower++;
}
Console.WriteLine(lower);
```

**Expected console output**
```0```

**Actual console output**
Around 9950, tested minimum is 9900 and tested maximum is 10000.

**Comment by AlexejheroYTB** [comment]
Just did a bit more testing, this issue seems to happen with all classes which extend `Human`, including `Human` itself. The issue doesn't seem to be regarding the `SoftwareUser` class, so I'm updating the title of this issue.

**Comment by Va1a** [comment]
+1 On this, I see this issue happen a lot as well

**Comment by AlexejheroYTB** [comment]
The author of the project seems to be inactive. His last contribution was in 2017. I don't see this issue being fixed anytime soon, maybe someone can fork the project and create a fix for this?

**Comment by Va1a** [comment]
#26 I have created a pull request, hopefully the maintainer will accept it.

**Comment by Alexejhero** [comment]
Associated PR was closed, i think this is intended behaviour.
