### ISSUE TITLE
Bug not fixed for over 1 year

### ISSUE THREAD

**Issue by jsphwllng** [god/earth#24]
Corona virus still present please remove.

**Comment by Nalin-2005** [comment]
The remove_sickness.py has not been executed, so the disease is not going away. Hope god executes it soon.

**Comment by SixBeeps** [comment]
> The remove_sickness.py has not been executed, so the disease is not going away. Hope god executes it soon.

@god any update on this? been dealing with this bug for quite a while 🙏🙏

**Comment by jsphwllng** [comment]
Seems to be a feature at this point..
