### ISSUE TITLE
Night seems too long on south pole

### ISSUE THREAD

**Issue by TheGreyDiamond** [god/earth#31]
Just a weird seemingly random bug:
Night seems to stay wayyyyy to long when on south pole, seems to happen every year at around January.
Fixing this however would probably make a lot of science people very very mad. So just so you know, no fix is needed.

**Comment by god** [comment]
Have you considered moving north?

**Comment by TheGreyDiamond** [comment]
Yeah, I have, though that does not fix the issue. Currently, it is happening again. Also, there are weird green things in the sky.

**Comment by TheGreyDiamond** [comment]
Havn't seen it in a while. Seems fixed.
