### ISSUE TITLE
[Feature Request]: Extend time of day form 24 to 30 hours

### ISSUE THREAD

**Issue by thomaspink** [god/earth#5]
As life gets more and more stressful and i got a lot work to do, it would be really helpful to extend the time per day from 24 hours to 30 hours.

Proposed Tasks:
* Let Earth spin slower so a day is now 30 hours.
* Adjust moons orbit to match the 30 hours.
* Adjust life (human body, ...) to this new cycle.
* Adjust orbit of earth around the sun to fix the issue we will get with the year (maybe optional).
* Adjust suns more intense radiation to match the current status on earth (also climate).
* Fix temperature issue: as we spin slower there will be a wider range of temperatures (days are hotter as sun shines longer, nights are colder)

Question: Maybe we should move this issue to the solar system repo: https://github.com/god/solar_system

Let's discuss

**Comment by MitchTalmadge** [comment]
The temperature issue could be hard to fix. We could try moving Earth a bit further from the Sun, but that might make the nights very cold. I propose a geo-stationary space heater to help the night be a bit warmer.
I have drawn a diagram to help illustrate:

![image](https://cloud.githubusercontent.com/assets/8848080/25884613/d0aec12c-3510-11e7-8c95-b5d6b0bedb46.png)

Thoughts on this plan?

**Comment by god** [comment]
Who's paying for the electricity to power this space heater?

**Comment by rosescooper** [comment]
Mexican!

**Comment by god** [comment]
That'll never happen!
